# SpringBoot 앱용 gitlab-ci 파이프라인
# - 머지 요청 시 테스트, 태그 생성 시 도커 이미지 빌드하는 파이프라인

# 시나리오
# Stage 1: test
#   master, develop 브랜치에 대해 Merge Request 시 gradle test 진행하는 스테이지
#   1-1 test-gradle job
#     * gradle test 진행. 실패 시 Merge 버튼 비활성화 (실패할때도 Merge 할 수 있도록 프로젝트 Setting에서 설정 변경 가능)
#     * gradle test 결과 리포트 깃랩 MR 화면 및 Job 상세 화면에서 확인 가능
#     * gradle jacoco 플러그인으로 코드 커버리지 체크
#   1-2 visualize-coverage job
#     * jacoco 결과 리포트를 cobertura 플러그인으로 가공해서 MR Changes 화면에서 코드 커버리지 확인할 수 있도록 추가
# Stage 2: analyze
#   master 브랜치에 Merge 커밋이 올라오면 정적 코드 분석 진행하는 스테이지
#   2.1 analyze-code
#     * Sonarcube 등을 이용해서 정적 코드 분석 진행
# Stage 3: package
#   배포를 위해 도커 이미지를 생성하고, harbor 저장소에 푸시하는 스테이지
#   3-1 build-docker
#     * gradle bootBuildImage 명령어를 통해 스프링부트앱을 도커 이미지로 패키징
#     * harbor 도커 이미지 저장소로 패키징된 이미지 푸시
# Stage 4: deploy
#   Continuous Delivery 를 위해 GitOps 저장소에 변경사항 커밋하는 스테이지
#   4-1 deploy-gitops
#     * 쿠버네티스 리소스가 저장된 GitOps 저장소 클론
#     * 3-1에서 생성한 도커 이미지 버전 정보를 쿠버네티스 리소스(yaml 파일)에 업데이트하여 커밋
#     * 원격 GitOps 저장소에 푸시

# CI job 별로 별도 명시한 이미지가 없을 때 사용할 디폴트 이미지
#  - docker executor 로 설치된 Gitlab-runner는 Job을 실행하기 위해서 도커 컨테이너를 생성하며 이 컨테이너를 실행하기 위한 이미지를 작성함
#  - 아래 docker:{version} 이미지는 alpine 리눅스 위에 도커:{version} 만 설치된 공식 이미지임
#  - image: ubuntu:19.04   등을 사용해서 우분투 이미지를 디폴트 이미지로 사용해도 됨
# 각 팀에서 판단해서 디폴트 이미지를 정해서 작성하면 되며
#  - job 별로 사용할 이미지를 각각 명시하는걸 추천
#  - 모든 job 에서 같은 이미지를 사용한다면 디폴트 이미지만 명시해주면 job 에 이미지를 작성하지 않아도 디폴트 이미지가 사용됨
image: docker:19.03.12

stages:
  - test
  - analysis
  - package
  - deploy

variables:
  HARBOR_URL: 'harbor.wapl.ai'
  DOCKER_PROJECT: 'wapl-dev'
  GITOPS_REPOSITORY: ''

# gitlab-ci "Job" 정의
test-gradle:
  # "gradle-test" job 이 속해있는 stage
  stage: test

  # Job을 실행할 docker image 작성
  # - docker hub에 올라간 공식 이미지를 사용해도 되고, 개인 도커 허브에 public 으로 올린 이미지를 사용해도 됨
  # - 아래 예에서는 gradle test 를 실행하기 위해 gradle:7.4과 openjdk11 이 포함된 공식 이미지를 베이스로 사용했음
  image: gradle:7.4-jdk11
  rules:
    # 마스터 브랜치나 develop* 브랜치에 머지 리퀘스트가 올라올 때
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^develop.*$/ )
    #- if: $CI_PIPELINE_SOURCE ==  "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "samsung-etech"
    # 마스터 브랜치에 커밋이 올라올 때
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "If project is built, run test code"
    - ./gradlew --build-cache --gradle-user-home cache/ test

    # jacoco 리포트가 존재하면 coverage 작성
    - |-
      if [ -f build/reports/jacoco/test/html/index.html ]; then
        cat build/reports/jacoco/test/html/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/'
      fi
  coverage: /Total.*?([0-9]{1,3})%/
  cache:
    key: gradle-cache-${CI_PROJECT_NAME} # gradle 캐시를 저장하기 위한 key
    paths:
      # 캐시 경로는 project 경로를 기준으로 상대경로를 작성하면 됨.
      # 디폴트 gradle 캐시 경로는 ${HOME}/.cache 인데 gitlab-runner는 project 하위 경로가 아닌 것들은 캐싱하지 못함
      # --gradle-user-home cache/ 옵션을 통해서 project 하위의 cache 폴더를 gradle 캐시 경로로 사용
      - cache/wrapper
      - cache/caches
  artifacts:
    reports:
      junit: build/test-results/test/**/TEST-*.xml  # unit test report
    paths:
      - build/reports/jacoco/  # jacoco code coverage report
  tags:
    - pl2-2

# MR > Change 화면에서 코드 커버리지 확인 가능하도록 표시하는 플러그인
visualize-coverage:
  stage: test
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  dependencies:
    - test-gradle
  needs: [ "test-gradle" ]
  rules:
    # 마스터 브랜치나 develop* 브랜치에 머지 리퀘스트가 올라올 때
    - if: $CI_PIPELINE_SOURCE ==  "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE ==  "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^develop.*$/
    #- if: $CI_PIPELINE_SOURCE ==  "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "samsung-etech"
    # 마스터 브랜치에 커밋이 올라올 때
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - python /opt/cover2cover.py build/reports/jacoco/test/jacocoTestReport.xml $CI_PROJECT_DIR/src/main/java/ > build/cobertura.xml
  artifacts:
    reports:
      cobertura: build/cobertura.xml
  tags:
    - pl2-2

# 마스터 브랜치에 커밋이 올라올 때, 정적 코드 검사
analyze-code:
  stage: analysis
  script:
    # 코드 분석 실행 스크립트
    - echo "After commits merged, run static/dynamic analysis."

  only: # MR 시 항상 테스트 실행
    - master
  tags:
    - pl2-2

# 도커 이미지 빌드 job
build-docker:
  stage: package
  image: docker:19.03.12
  # 아래 서비스는 Docker-in-Docker (dind)를 위한 설정
  # - docker-build 라는 Job이 현재 docker:19.03.12 이미지로 생성된 컨테이너에서 실행되고 있는 상태
  # - 도커 컨테이너 안에서 다시 docker 명령어를 수행하기 위해 나온 개념이 docker-in-docker
  # - docker build 또는 docker push 등과 같은 명령어를 수행하려면 아래 services 를 복사해서 사용하기 바람
  services:
    - name: docker:19.03.12-dind
      alias: docker
      command: ["--tls=false"]

  # DinD 이미지는 alpine 위에 docker 와 dind 서비스만 올라간 이미지이기 때문에 별도로 gradle-7.4, openjdk-11 을 설치 하는 스크립트 추가
  before_script:
    - apk update
    - apk add openjdk11
    - apk add bash curl zip && curl -s "https://get.sdkman.io" | bash
    - bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && sdk version && sdk install gradle 7.4"

    # harbor.wapl.ai 에 이미지 푸시하기 위해 로그인 진행
    - echo "---- Docker login"
    - echo "$HARBOR_PASSWORD" | docker login -u "$HARBOR_USER" "$HARBOR_URL" --password-stdin
  script:
    - echo "build docker image with tag ${CI_COMMIT_TAG}"
    - |-
      ./gradlew --build-cache \
                --gradle-user-home cache/ \
                bootBuildImage \
                --imageName=${HARBOR_URL}/${DOCKER_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} \
                -Pprofile=prod
    - docker tag ${HARBOR_URL}/${DOCKER_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} ${HARBOR_URL}/${DOCKER_PROJECT}/${CI_PROJECT_NAME}:latest

    - echo "Deploy docker image ${DOCKER_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
    - echo "docker push ${HARBOR_URL}/${DOCKER_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
    # harbor.wapl.ai/wapl-ci/{project_name} 밑에 이미지 푸시
    - docker push ${HARBOR_URL}/${DOCKER_PROJECT}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
    - docker push ${HARBOR_URL}/${DOCKER_PROJECT}/${CI_PROJECT_NAME}:latest
  only:  # 태그 작성 시 도커 이미지 빌드
    - master
    #- samsung-etech
    - tags
  except:
    - branches
  cache:
    key: gradle-cache-${CI_PROJECT_NAME} # gradle 캐시를 저장하기 위한 key
    paths:
      - cache/wrapper/
      - cache/caches/
  tags:
    - pl2-2

# GitOps 저장소에 빌드한 도커 이미지 버전을 수정하는 job
deploy-gitops:
  stage: deploy
  needs: ["build-docker"]
  # 가장 가벼운 alpine 이미지에 깃만 설치해서 사용
  image: alpine:3.15
  only:
    - master
    #- samsung-etech
    - tags
  except:
    - branches
  variables:
    # GitOps 정보들을 환경변수 파일이나 프로젝트 환경변수로 분리 해야 함
    GITOPS_HOST: 'demogit.tmaxcloud.com'
    GITOPS_PROJECT_PATH: 'wapl-cicd/gitops'
    GITOPS_BRANCH: 'wapl-dev'

  # alpine 이미지에 깃 설치 후 gitops 저장소 clone
  before_script:
    - apk update && apk add git
    - pwd
    - git clone "https://${GITOPS_USERNAME}:${GITOPS_TOKEN}@${GITOPS_HOST}/${GITOPS_PROJECT_PATH}.git" "${CI_COMMIT_SHA}"
    - cd ${CI_COMMIT_SHA}
    - git config user.email "${GITOPS_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config user.name "${GITOPS_USER_NAME:-$GITLAB_USER_NAME}"
  script:
    - git checkout ${GITOPS_BRANCH}
    - cd ${CI_PROJECT_NAME}
    - pwd

    # update gitops
    - sed -i "s;image:\ $HARBOR_URL/$DOCKER_PROJECT/$CI_PROJECT_NAME:.*\+;image:\ $HARBOR_URL/$DOCKER_PROJECT/$CI_PROJECT_NAME:$CI_COMMIT_TAG;g" note-deployment.yaml
    # commit to Git
    - git add .
    - |-
      CHANGES=$(git status -- porcelain | wc -l)

      if [ "$CHANGES" -gt "0" ]; then
        git status
        git commit -m "${CI_PROJECT_NAME}_${CI_COMMIT_TAG}"
        git push
      fi

  tags:
    - pl2-2
