spring:
  datasource:
    url: jdbc:tibero:thin:@220.90.208.123:8629:tibero
    driver-class-name: com.tmax.tibero.jdbc.TbDriver
    username: cms
    password: cms

  aop:
    proxy-target-class: true

  # jpa Setting
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        '[format_sql]': true
    #        show_sql: true
    #        use_sql_comments: true
    database-platform: ai.wapl.global.config.CustomOracle10gDialect

  # hibernate logging
  # logging.level.org.hibernate=info
logging:
  level:
    '[org.hibernate.SQL]': debug

#firebase_service_key path
firebase:
  service:
    key:
      path: firebase_service_key.json
  apns:
    topic: com.tmaxanc.teespace.qa

# server info
websocket:
  server:
    url: http://192.168.152.97:8888
wapl:
  com:
    server:
      url: https://teespace.com

noteapi:
  default:
    schema: CMS
  localhost:
    schema: DOM_B2B_4
